"""empty message

Revision ID: 383d1d75bf93
Revises: 86fdd535eb60
Create Date: 2020-12-17 14:08:43.848661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383d1d75bf93'
down_revision = '86fdd535eb60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'request', 'course', ['course_id'], ['id'])
    op.create_foreign_key(None, 'students_in_course', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_in_course', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    # ### end Alembic commands ###
